name: attendance_app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - dlib                  # Pre-built (Fast)
  - face_recognition      # Pre-built (Fast - stops the compilation)
  - pip
  - pip:
    - opencv-python-headless
    - streamlit
    - streamlit-webrtc
    - av
